// prisma/seed-data/scripts.ts
export interface SeedScript {
  title: string;
  description: string;
  storyText: string;
  coverImage: string;
  playerCount: string;
  duration: string;
  difficulty: string;
  genre: string;
  pricePerPerson: number | null;
  priceGroup: number | null;
  isContactOnly: boolean;
  bookingNote: string | null;
  published: boolean;
}

export const seedScripts: SeedScript[] = [
  {
    title: "洗劫倫敦所有的玫瑰",
    description: "極致純愛浪漫 / 可愛小丑 / 菲爾酒店歡迎您",
    storyText:
      "一夜之間，全倫敦所有的玫瑰都失竊了。沒有人知道是誰將它們洗劫一空，更沒有人知道，那個人究竟為什麼要偷走玫瑰。同一時間，新開的菲爾酒店裡正坐著六個人，他們是新來到這裡的住客。雖然看起來每個人都稀鬆平常，但他們身上卻都有著各自不可思議的離奇故事……\n\n角色：斯黛拉（女）、娜芙蒂蒂（女）、柯萊蒂（女）、阿爾芒（男）、阿努（男）、羅素（男）",
    coverImage: "/scripts/93aa9eb19556c35b9a1130b29ffe7a48.png",
    playerCount: "6人- 3男3女",
    duration: "5小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "情感",
    pricePerPerson: 850,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約此遊戲請直接私訊粉專小編：IG @larpplayhardtw 或官方 LINE（https://lin.ee/n4sr3Lg）。非玩硬劇本館上架劇本，無法使用玩硬相關優惠。",
    published: true,
  },
  {
    title: "高天原-主神的選拔賽",
    description: "超熱血機制本/企鵝榮譽出品/可反串/華麗道具換裝",
    storyText:
      "世界初開，天地間只有混沌、了無生機，直到一對兄妹神的到來，他們名叫「伊邪那岐」和「伊邪那美」。而這次，是屬於他們兒女，以及世間萬物之神的故事。有愛、有恨、有熱血沸騰！八位神明大人，究竟誰能成為高天原的主神，統領世間萬物呢？",
    coverImage: "/scripts/b87ba45c21013f38b41b266fe80d7cd8.png",
    playerCount: "8人- 4男4女",
    duration: "7~8小時",
    difficulty: "歡樂熱血⭐⭐⭐⭐⭐",
    genre: "歡樂",
    pricePerPerson: 1000,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "上路",
    description: "最新/驚嚇橋段",
    storyText:
      "夜裡的公路駛過一台越野車，車上的孩子們一聲不吭，副駕駛座上的女人似乎是發了狂，不斷回過頭看向後座數著「1...2...3...」好不容易算好數量，女人終於放心地看向前方……「不對……」女人喃喃自語「他……不是已經死了嗎……」\n\n＊本遊戲遊戲過程中會有驚嚇橋段＊\n若有心臟病、高血壓、密閉空間恐懼症、嚴重氣喘、孕婦、癲癇等，不建議參與本活動，請評估自行身心狀況後再進行遊戲，若有特殊突發狀況，歡迎告知櫃檯或客服人員\n\n角色介紹：\n達澤明：男，爸爸。\n張雅文：女，媽媽。\n張卓君：男，哥哥。\n達雯菁：女，妹妹。\n阿花：女，妹妹。",
    coverImage: "/scripts/54f12c248d574721f786a7830f783e82.jpg",
    playerCount: "5人- 2男3女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐⭐⭐",
    genre: "恐怖",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "誠如惡魔低語",
    description: "惡魔中二/五人歡樂/新手入門/可反串",
    storyText:
      "秋葉市的惡魔怪談流傳已久，各種離奇命案不斷發生，這一切的背後，似乎又牽扯出一個神秘組織。多方勢力匯聚一堂，一場針鋒相對的較量即將展開。各懷鬼胎的人們啊，究竟誰才是真正的惡魔?",
    coverImage: "/scripts/beac01f60b81ac00ca875643cb9f183b.jpg",
    playerCount: "5人- 3男2女",
    duration: "3小時",
    difficulty: "難度⭐",
    genre: "新手推薦",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "七日囚徒",
    description: "#精分超強彩蛋 #為愛奉獻所有 #生日快樂",
    storyText:
      "＊「病嬌男孩系列」彩蛋本，可跳著玩，無換裝＊ 微驚嚇橋段\n\n我可以隱約看見皮下青色的血管，曾無數次幻想著，割破它……可我無法結束自己的生命，因為我的七隻貓咪不能再流浪：小一、小二、小三、小四、小五、小六、小七。它們有著對我毫無保留、傾盡所有、始終如一的仰慕和依賴感，這是我從未得到過的，某種愛。",
    coverImage: "/scripts/d5a354cfa59d978ee15f7416347d6009.jpg",
    playerCount: "6人- 男女不拘",
    duration: "4~4.5小時",
    difficulty: "難度⭐⭐",
    genre: "推理",
    pricePerPerson: 850,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "神木屋",
    description: "微恐情感/伊藤潤二/城限/不建議反串/提供換裝",
    storyText:
      "＊本故事經「伊藤潤二」授權，並由「伊藤潤二精選集」改編＊\n＊訂場時間由於「系統設置」關係，較為硬性。若需調整或於特殊時段訂位，請直接聯繫客服。\n\n東京郊外，一座老宅長年矗立在無人問津的荒山叢林中，新的屋主神木彻(音同撤)在此開辦民宿\"神木屋\"，卻又給客人們豎立許多古怪的規矩，有關它的怪談傳說漸漸擴散開來，膽小之人自然敬而遠之，神木屋越發荒涼。S大學\"超自然研究協會\"的5名社員偏偏不信邪，在畢業前夕結伴前往這棟古宅中留宿了一夜，第二天都毫髮無損地回到了學校，謠言似乎不攻自破。五年之後，曾經的社員們重回當年探險的老宅，誰知一夜過後，某社員竟慘死在反鎖的屋中。隨著案件的搜查，現實與人心的反轉漸漸顯露，多年的愛恨與殺戮終於隨著古宅的秘密撥開了重重迷霧......\n\n＊本遊戲遊戲過程中會有驚嚇橋段＊\n若有心臟病、高血壓、密閉空間恐懼症、嚴重氣喘、孕婦、癲癇等，不建議參與本活動，請評估自行身心狀況後再進行遊戲，若有特殊突發狀況，歡迎告知櫃檯或客服人員\n\n角色介紹：\n坂田一郎：男，27歲，寬厚而缺乏個性，坂田雜誌社社長。\n栗山亮：男，18歲，熱情殷勤，坂田雜誌社職員。\n淺野慎司：男，27歲，冷漠寡言，前坂田雜誌社編輯。\n酒井美和子：女，27歲，性感而富有主動性，前坂田雜誌社秘書，現無業，坂田前妻。\n上杉千惠：女，27歲，敏感毒舌，前坂田雜誌社簽約作家。\n神木葵：女，17歲，天真單純，神木屋年輕的看宅人。",
    coverImage: "/scripts/67f693b412546053dcb14d86cd42910a.png",
    playerCount: "6人- 3男3女",
    duration: "5小時",
    difficulty: "推理⭐⭐⭐",
    genre: "恐怖",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。系統限訂晚場，需白天場次請洽客服。",
    published: true,
  },
  {
    title: "還願",
    description: "雙主持恐怖本/信仰與真相/你還願了嗎？",
    storyText:
      "＊備註：遊戲內容與赤燭遊戲「還願」無關＊\n\n六名死囚，一名心理醫生。六名警員，一名正義刑警。六名同學......六名......嗎？一則20年前的故事，一個20年前的秘密。是巧合產生了信仰，還是信仰造就了巧合？你許願了......，但......你還願了嗎？",
    coverImage: "/scripts/2721975a7aab017e0718e3968fdc3eb6.png",
    playerCount: "6人- 不限性別",
    duration: "4~5小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "恐怖",
    pricePerPerson: 1100,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "盛典！死亡逃生術",
    description: "歡樂鬥智/職業魔術師親手打造/從頭到尾都是伏筆",
    storyText:
      "這世界有正義就有邪惡。而我們，是這世界最邪惡的組織「殺人蜂」的成員！今天，我們的任務就是解決掉那些自以為正義的小丑們－「單車俱樂部」。\n\n角色：傑夫、胡安、麥可、潔西卡、蘭斯、羅德、愛麗絲",
    coverImage: "/scripts/083fe29f1875bdfb2ba2f34621692d3c.jpg",
    playerCount: "7人- 5男2女",
    duration: "4小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "歡樂",
    pricePerPerson: 800,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "喵的名字",
    description: "情感本/城市限定/不建議反串/提供滿滿貓耳",
    storyText:
      "「零國」之中有一座美麗的城鎮，被稱為「忘憂城」，這裡的居民都是動物。不久前，忘憂城裡忽然發生了多起離奇的失蹤案，甚至包括了企鵝公司的董事長和他旗下「鹹魚樂隊」的成員。\n\n角色：黑貓教父、土貓鍵盤手、布偶貓吉他手、仙女貓主唱、波斯貓爸爸、大女兒、二女兒、貍花貓媽媽",
    coverImage: "/scripts/485cb066823ebaffb2177dfe6c5fea39.jpg",
    playerCount: "8人- 4男4女",
    duration: "3小時（僅提供貓耳，無服裝換裝）",
    difficulty: "推理難度⭐",
    genre: "情感",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "帶我回家",
    description: "微恐情感/獵奇都市傳說/提供換裝",
    storyText:
      "一個偏遠的小鎮，一群可愛的孩子，在一檔神祕的深夜節目後，平靜不復存在。「帶我，回家….」這是甚麼聲音？只要你答應了，它就會一直陪著你，直到，永遠。\n\n角色：里德‧卡特（10歲）、艾薩克‧霍爾（10歲）、安妮・肯尼迪（8歲）、伊莎貝爾・羅德尼（8歲）、秋原陽紀（8歲）",
    coverImage: "/scripts/86297205829a5f06399924fe11e5c8b9.png",
    playerCount: "5人- 3男2女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐",
    genre: "情感",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "偉大的一生",
    description: "#5人情感 #沉浸無推理 #不建議反串",
    storyText:
      "命運是世界上最爛的編劇。而我，是這個人生最偉大的演員。「你來應聘的嗎？想要做什麼職位？」「總統，或者還有更好的也行。」「呃，那您都會什麼？」「蒙娜麗莎我畫的，電燈泡我發明的，命運交響曲我譜的，這個劇本我寫的。」",
    coverImage: "/scripts/ae41420c0045070b26b642f94cab3eeb.png",
    playerCount: "5人- 3男2女",
    duration: "4~4.5小時（純沉浸情感本，無推理橋段）",
    difficulty: "難度⭐",
    genre: "情感",
    pricePerPerson: 850,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "十五",
    description: "寵物情感/狗派的你快來玩/可反串",
    storyText:
      "我們的十五年，是他們的一輩子。他們用一輩子的時間愛著我們，只希望我們能夠永遠快樂。快啊！抱上你的毛孩！一起出發探險！從怪人雲集的社區，到狗狗全體消失大會，最後來到瘋狂遊樂場。",
    coverImage: "/scripts/deca4dbf090ca8771909fa6b08fe5d1d.png",
    playerCount: "6人- 3男3女",
    duration: "3.5小時",
    difficulty: "推理難度⭐",
    genre: "情感",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "一點半",
    description: "經典怪談/海龜湯/誰在說謊/鬼故事大會",
    storyText:
      "這個世界上有些人信佛，有些人信道，還有些人沒有信仰。但他們都怕寂寞，還更怕鬼......你呢？都市怪談協會，誠摯邀請所有寂寞孤獨且怕鬼的你們，一起尋求刺激，抱團取暖。\n\n角色：王磊（31男）、蕭榤（26男）、楊晶晶（28女）、李雨彤（26女）、姚金銘（24女）、余曉龍（33男）",
    coverImage: "/scripts/1bccc939fcc69fe9c34b279be89ba1af.png",
    playerCount: "6人- 3男3女",
    duration: "3小時（無換裝）",
    difficulty: "推理難度⭐⭐",
    genre: "恐怖",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "泉溪村",
    description: "陰陽師傳說/多重結局/可以無恐/4人超好揪",
    storyText:
      "＊初始設定為「微微恐」，無NPC，訂場時可勾選為「無恐」＊\n\n泉溪村，一個與世隔絕的山中村落......村中看似平靜，卻傳來一陣又一陣陰森的氣息。在這個陰陽之術出沒的年代，這四人會有什麼樣的故事與結局呢......\n\n角色：木原幸子（女）、長尾直人（男）、竹原奈奈（女）、池田賢（男）",
    coverImage: "/scripts/c121943bcbb637edbde965c747214e2e.png",
    playerCount: "4人- 2男2女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐",
    genre: "恐怖",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "迪賽普",
    description: "克蘇魯/教徒們贖罪吧/SAN0瘋起來",
    storyText:
      "＊本遊戲劇情部分描寫性與暴力，但遊戲過程一切正常。＊\n＊非恐怖本，僅部分環節會環境黑暗＊\n＊沒有任何章魚受到傷害＊\n\n你悠悠轉醒，腦子昏沉沉。你試圖想起些什麼，但腦海卻一片模糊。環顧四周，你身處一個點著些許蠟燭的詭異法陣中，右手緊握著一把左輪手槍，地上還有一枚彈殼。虛弱的你用盡力氣推開房門，扶在門框上喘氣時，幽深的迴廊陸續傳來開門聲音，走廊盡頭的一間房卻如死一般寂靜。迪賽普教派一年一度的洗禮日，八位信徒被選中接受洗禮，其中一位信徒卻死在了洗禮儀式上......迪賽普教大祭司震怒宣布神諭如果你們不能找出兇手，至高存在 將親自懲戒你們！\n\n角色介紹：\n文森特 男，極鯊幫首領，心狠手辣。\n波特哥 男，暗光會首領，及肩的長髮未曾過多打理，滄桑的面容給人陰沉的感覺。\n蒙德里安 男，英俊帥氣的陰柔男子，父親是貝克蘭德一個餐館老闆。\n瑪格麗特 女，普通的社區辦事人員，天生麗質、膚白貌美讓她擁有眾多追求者。\n薇薇安 女，普通的社區辦事人員，待人友善，金黃色的長髮尤為吸引人。\n桃樂絲 女，短髮有活力的女孩，臉色蒼白似乎有些憂鬱。\n奧莉維婭 女，中產家族的大小姐，脾氣溫和，酒紅色的秀髮讓她擁有眾多的追求者。",
    coverImage: "/scripts/c0b2866e24abec4d8b12258edb0a8f98.png",
    playerCount: "6-7人- 3男4女",
    duration: "3.5小時",
    difficulty: "推理難度⭐⭐",
    genre: "恐怖",
    pricePerPerson: null,
    priceGroup: 4200,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "病嬌男孩的戀愛日記",
    description: "精分日記超強續集/奉獻所有的愛/約定很重要",
    storyText:
      "＊「病嬌男孩的精分日記」續集，強烈建議先玩過原作；無換裝＊ 微驚嚇橋段\n\n虛弱，無比強烈的虛弱感，彷彿從泥沼中掙扎著爬出。看著手腕上的疤痕，以及過去我寫的那本日記，我才知道自殺後的我似乎沒死。這裡是平行時空嗎？重要的是，我們是蕭何，我們還活著。\n\n角色：六位蕭何（喜歡吃美食的、打電動的、打掃清潔的、看書的、運動的、怕黑的）",
    coverImage: "/scripts/2af729640c71a20a793807968b32bb01.png",
    playerCount: "6人- 男女不拘",
    duration: "3.5小時",
    difficulty: "推理難度⭐⭐",
    genre: "情感",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "病嬌男孩的精分日記",
    description: "細思極恐代表作/是真的日記/生日快樂",
    storyText:
      "我叫蕭何。我一生的時間，是別人的七分之一，生命的厚度卻是別人的七倍。為了能更好地同處於這具身體，我們分別取名星期一到星期天。我們之間從未打過照面，便條紙上的文字是我們溝通的唯一途徑。\n\n角色：七位蕭何（喜歡吃美食/打電動/打掃清潔/看書/宅在家/運動/怕黑的蕭何）",
    coverImage: "/scripts/036d2028d4c24192e6eb294cb8042e90.png",
    playerCount: "7人- 性別不拘",
    duration: "3.5小時（細思極恐，非嚇人恐怖本；無換裝）",
    difficulty: "推理難度⭐⭐⭐",
    genre: "推理",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "復生起源",
    description: "巫術瑪卡巴卡/超自然震動/一起尋找真理吧",
    storyText:
      "＊主推理、細思極恐，非恐怖本；建議先玩過「沙鯔孤兒院」或畸型屋系列＊\n\n永生，迄今人類不斷追尋著的終點，但要能求得永生，要用多少東西交換呢？今日，6位超自然能力者齊聚，一同探討起「永生之術」該如何實行，但......古堡的陰謀也隨之湧上......\n\n角色：康士坦丁、紅夫人、入殮者、夢之女巫、吉普賽女巫、祕客",
    coverImage: "/scripts/9ad19bb3c9d227630e7fcdac943c3aab.png",
    playerCount: "6人- 3男3女",
    duration: "3.5-4小時",
    difficulty: "推理難度⭐⭐⭐⭐",
    genre: "推理",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "精神病院3",
    description: "病院認真推理/對講機救命/神秘小房間",
    storyText:
      "故事發生在一間從未聽聞過的「神秘八號病院」，蓋在懸崖邊，進出都要靠直升機接送。但不論什麼精神疾病，只要來了都只要一下子就能好起來......而今天，你們被鎖在這間病院裡，到底要怎麼出去呢？\n\n角色：阿斌（男15）、阿布（男15）、阿雪（女45護理師）、莎莎（女15病人）、阿哲（男46護理師）、？？？",
    coverImage: "/scripts/b253156f6e1e9713397bdf1e999d8f2c.png",
    playerCount: "6人- 4男2女",
    duration: "3.5小時（可跳著玩，不需先玩1/2/4）",
    difficulty: "推理難度⭐⭐⭐⭐",
    genre: "推理",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "精神病院4",
    description: "開宗明義五個神經病/不瘋起來會卡關/恥力全開",
    storyText:
      "故事發生在那間超級有名的「六號精神病院」！現在是吃午餐的時間了，突然醫院裡來了一位沒看過的陌生人。他到底是誰！？而我又是誰？完蛋，突然忘了。\n\n角色：浪情、大黑、阿增、阿馨、巨基",
    coverImage: "/scripts/c85b487cb15db6c5dabf24db0fc34467.png",
    playerCount: "5人- 3男2女",
    duration: "3.5小時（建議先玩過「精神病院2」）",
    difficulty: "推理難度⭐⭐",
    genre: "歡樂",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "忍者",
    description: "日式歡樂機制本/可反串/提供換裝",
    storyText:
      "忍生們！揮舞你們的雙手！燃起你們的熱血！為了成為正式忍者而戰鬥吧！何為忍道？何為忠誠？何為強大？所謂忍者，即能忍耐常人所不能忍受之事之人。",
    coverImage: "/scripts/b0592460005139be355af3494f80ed56.png",
    playerCount: "5人- 3男2女",
    duration: "4小時",
    difficulty: "推理難度⭐⭐",
    genre: "歡樂",
    pricePerPerson: 850,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "它是龍",
    description: "#一起屠龍 #譜寫史詩 #多種職業與道具",
    storyText:
      "古老的大陸上坐落著兩座城堡。據說在很久以前，生活於此的還有一種獨特的生物：龍。不知道從哪一天開始，城裡突然傳出巨龍掠奪人類的財寶、搶走人類的子嗣的消息，鬧得滿城風雨。\n\n角色：龔特爾（男，王子）、哈根（男，魔法使）、齊格菲（男，獵人）、古德倫（女，祭司）、布倫希爾德（女，騎士）、神秘女子（女，德魯伊）",
    coverImage: "/scripts/1651329176688bcdd6fd03a0f712b456.png",
    playerCount: "6人- 3男3女",
    duration: "4小時",
    difficulty: "推理⭐⭐",
    genre: "歡樂",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "花吃了那女孩",
    description: "極細思極恐/沈浸還原/可反串/華麗換裝",
    storyText:
      "巫女，是這個年代最具權威的職業之一。要想成為巫女必須先經過艱難的「巫女試煉」，而今年的考官更是大家口耳相傳的「海兔老師」。而你們六位，為了各自的目的來到了這裡......\n\n角色：麻衣、雄二、麗山、四郎、小舞、琉彌",
    coverImage: "/scripts/efddd119aa26cfb1a535b7779e6190fe.png",
    playerCount: "6人- 3男3女",
    duration: "4小時（沈浸式體驗，會有適度肢體接觸）",
    difficulty: "推理⭐⭐⭐",
    genre: "恐怖",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "格林的花園",
    description: "超色十八禁/童話崩壞/可反串/提供換裝",
    storyText:
      "＊劇情搧色（如同讀一本黃色小說），但遊戲過程一切正常，並無色色體感發生＊\n\n很久很久以前，有一個美好的國家，國王是一位善良的老人，娶過兩位妻子，有四個女兒。傳說上天感念他的善良，賜予他一個小公主，16年後，老國王卻在午夜12點鐘聲響起之時離奇死亡。\n\n角色：琳娜公主、瑪利亞、仙度瑞拉、姍琵女士、伊茲舍、芭黛、艾克斯、弗拉格",
    coverImage: "/scripts/06eadaa53ffbc7e8333b78c19fe07f2f.png",
    playerCount: "8人- 3男5女",
    duration: "4小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "情感",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "白衣死神",
    description: "新手大推/美式劇本殺/別處玩不到的驚喜結局",
    storyText:
      "＊別名\"死穿白\"／\"Death wears white\"；可能有肢體接觸(非恐怖)＊\n\n底特律市區最有名的布萊頓醫院急診室，醫生漢斯身穿白袍倒在了實驗室的地板上，背後身中兩槍身亡。究竟是誰對漢斯醫生下了手？挾持犯又是想要得到什麼？\n\n角色：德雷克、西爾維亞、理查、依萊恩、蓋爾、湯姆、東尼(8人)、法蘭克(8人)/法蘭尼(7人)",
    coverImage: "/scripts/d703da3085dd12a9b825db3eb42d5ad5.png",
    playerCount: "7-8人- 5男3女",
    duration: "3小時",
    difficulty: "推理難度⭐",
    genre: "新手推薦",
    pricePerPerson: null,
    priceGroup: 4000,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "雨夜感染者",
    description: "機制情感/4人超好揪/可反串/提供換裝",
    storyText:
      "這是一個只有黑夜的世界，總是下著紅色的雨。你們被困在爬滿紅色藤蔓的房子裡，房門外似乎藏著某種生命跡象。「雨夜兩大守則：1.永不停工 2.絕不開門」\n\n角色：敲牆人、粉刷匠、水泥工、開窗者",
    coverImage: "/scripts/9f27d977354a6fd901b7e91ba22e9546.jpg",
    playerCount: "4人- 感染者四名",
    duration: "3.5小時（非恐怖本，溫馨情感本）",
    difficulty: "推理難度⭐⭐",
    genre: "情感",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "新屋-1988",
    description: "鹿人口碑保證/恐怖本/中式怪談/可反串/提供換裝",
    storyText:
      "「搬新屋的第一年，一定要在新屋一起過新年喔......」除夕夜，全家人都回來過年了，自從搬到這間新屋後，總是發生一些奇怪的事：夜裡敲牆的聲音、孩子相繼失蹤......\n\n角色：趙興川（男）、張鐵梅（女，母親）、余美鳳（女，新太太）、劉鑫（女，前妻）、蘇紅（女，幫傭）、？？？（男）",
    coverImage: "/scripts/014241ed40337c08101bf6913677697e.jpg",
    playerCount: "6人- 2男4女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐⭐⭐",
    genre: "恐怖",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "青玉賭坊之玲瓏緣",
    description: "賭博賭翻天/古物大拍賣/走心大擂台/提供換裝",
    storyText:
      "大唐開元年間，扶風縣出現了名為「玲瓏匣」的寶貝，將於知名的青玉賭坊中拍賣。據說持有這匣子之人將獲得天命加持，甚至長生不死。七位客人懷揣著不同目的踏入賭坊......\n\n角色：趙恆（黑衣男子）、蕭諾熙（青衣少婦）、王安蒲（華服男子）、沈千尋（布衣男子）、劉士安（白衣少年）、蘇晚棠（黃衣少女）、柳言柒（紫衣少女）",
    coverImage: "/scripts/76032771ea64eb0d31e17e3e7d145102.png",
    playerCount: "7人- 4男3女",
    duration: "5小時",
    difficulty: "推理難度⭐⭐⭐⭐",
    genre: "情感",
    pricePerPerson: 900,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "沙鯔孤兒院",
    description: "孤兒院/反轉再反轉/歡樂詭譎/面具問號人",
    storyText:
      "在薩默賽特的郊區有一座私人宅邸，被格洛里院長買下來並改建成孤兒院。這些年孤兒院不好的名聲以及詭異的傳聞一而再地傳往外面，格洛里院長決定辦一個新生歡迎會。\n\n角色：歐文、羅琳、艾達、舒蒂、霍爾、？？？",
    coverImage: "/scripts/7b083cafa2d8ba05c7390041d562dc1d.png",
    playerCount: "6人- 2男4女",
    duration: "3小時（歡樂推理本，非恐怖本，但有細思極恐劇情）",
    difficulty: "推理難度⭐⭐",
    genre: "歡樂",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "芙蓉庄",
    description: "新手大推/歡樂恐怖機制本/可反串/提供換裝",
    storyText:
      "赫赫有名的林家，在遠離塵囂的郊區蓋了一棟華美的別墅叫做「芙蓉庄」。今日林家的主人林萬貫先生即將宣讀遺囑，居然來了兩位律師？而此時，翻遍了整間屋子怎麼樣也找不著林萬貫老爺......\n\n角色：林水水、林冬華、林春安、林秋生、李運強、王正英、孟嫂",
    coverImage: "/scripts/819891a228de8a80867ff45843046a74.png",
    playerCount: "6-7人- 4男3女",
    duration: "3.5小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "新手推薦",
    pricePerPerson: null,
    priceGroup: 4500,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "薔花與鳶尾",
    description: "歐風詭宅/神秘寶藏/吃人的屋子/自己的故事自己演",
    storyText:
      "「這間屋子會吃人......」故事發生在沃里克郡郊區一座老舊的宅邸中，不知為何家中多名女傭離奇失蹤人間蒸發。該邸宅曾是吸血女伯爵伊麗莎白的爵宅居所。\n\n角色：艾薇（女，小女兒）、艾芮絲（女，大女兒）、瑪莉提絲（女，祖母）、查佐（男）、約書亞（男，家庭教師）、范（男，路人）",
    coverImage: "/scripts/ae91b5e3bd584b3b0f7a344950a654f8.jpg",
    playerCount: "6人- 3男3女",
    duration: "3.5小時（主推理、演繹、細思極恐，非恐怖本；線索需自行演繹）",
    difficulty: "推理難度⭐⭐",
    genre: "推理",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "惠子-4885",
    description: "新手/恐怖本/可反串/提供換裝",
    storyText:
      "在東京大學藝術學院，流傳著一些校園怪談，其中最出名的就是「4885教室的紀香」。傳聞28年前有位女學生在4885教室裡上吊自殺，從此學校就開始有了鬼影的傳言。\n\n角色：山下浩二（男）、赤坂娜娜（女）、井野一輝（男）、後藤大雄（男）、相田明日香（女）",
    coverImage: "/scripts/173c6d86a64966c1d3687591ff37be93.png",
    playerCount: "5人- 3男2女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐",
    genre: "新手推薦",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "畸形屋2",
    description: "塔羅牌/召靈儀式/可反串/全台獨家",
    storyText:
      "這裡是一座離威爾特碼頭不遠的小島，小島上的這座私人公館似乎正被詛咒著......這是惡魔的低語、亡靈的詛咒......今晚是血月之日。這個被黑暗侵蝕的家族究竟隱瞞了什麼不為人知的秘密？\n\n角色：蘭伯特（男主人）、克蘿伊（女主人）、赫莎、法瑞絲、丹迪、戴爾",
    coverImage: "/scripts/22fb6be6035d2f69dbaca940e04d068e.jpg",
    playerCount: "6人- 3男3女",
    duration: "3.5小時（主推理、細思極恐，恐怖度低；不需先玩「畸形屋」）",
    difficulty: "推理難度⭐⭐⭐⭐",
    genre: "推理",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "繡花鞋-1980",
    description: "＊全新重製劇本＊/大恐怖本/觀落陰/人性抉擇",
    storyText:
      "1980的台北，台灣正值經濟起飛，守舊和先進思想的碰撞下，衍生出不同的人生價值觀。但永恆不變的是......『善惡終有報』農曆七月十日，雨夜。時辰已到......\n\n角色：方媛（女20）、李天瑜（女20）、杜擎宇（男23）、鄭越（男52）、鑫紹輝（男58）、楊波（男21）",
    coverImage: "/scripts/144f3e50cee4765cd1a427ed323a72ba.png",
    playerCount: "6人- 4男2女",
    duration: "4小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "恐怖",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "消失的新娘",
    description: "＊入坑首選＊/微恐還原/可反串/提供換裝",
    storyText:
      "「昨日黃土隴頭送白骨，今宵紅燈帳底臥鴛鴦」周家所在的這個小鎮，人來人往，魚龍混雜，歷來多詭奇靈異之事。下午賓客紛紛散去，到了晚上只剩下周子陽、朱方杰、曲若清三人小聚，不知多久，三人似不勝酒力，紛紛醉倒過去......\n\n角色：周子陽（男，新郎官）、曲若清（女，大小姐）、朱方杰（男，文人）、柳小韵（女，下人）、吉祥（男，短工）",
    coverImage: "/scripts/1042dc1d4c39727963b51d7cc5b59163.png",
    playerCount: "5人- 3男2女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐",
    genre: "新手推薦",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "萌殺女僕咖啡廳",
    description: "新手大推/全台原創獨家/華麗換裝/班傑明作品",
    storyText:
      "主人，歡迎回到「羅莉喵喵」女僕咖啡廳。今晚是平安夜，女僕長最喜歡的節日。不過，沒想到除了女僕們與兩名來訪客人外，女僕長竟然還驚見了一具屍體！但死者似乎有些眼熟。\n\n角色：賽琳（女僕，漫畫家）、玥鴉兒（女僕，占卜師）、憐蝶（女僕，樂團主唱）、愛麗絲（女僕，Coser）、日孝誠（男，尼特族）、史馱壽（男，攝影師）",
    coverImage: "/scripts/7ae9b9ac9243077d79ba7c46dbd53870.png",
    playerCount: "6人- 2男4女",
    duration: "3.5小時",
    difficulty: "推理難度⭐⭐",
    genre: "新手推薦",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "精神病院1",
    description: "微恐情感/懸疑推理/可反串/提供換裝",
    storyText:
      "SEVEN精神病院是一個十分有名的精神病院。傳言只要進了這家精神病院的患者百分之九十都可以健康出院。而今天，故事將在這神秘的精神病院裡拉開序幕⋯⋯\n\n角色：三土（男，護理師）、童洲（男，護理師）、萱萱（女，護理師）、斯特（男，病患）、李超（男，病患）、未來（女，病患）",
    coverImage: "/scripts/0c457563e9427c6b3aac697d04071b4b.png",
    playerCount: "6人- 4男2女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "推理",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "精神病院2",
    description: "新手大推/新手歡樂/笑到流淚/可反串/提供換裝",
    storyText:
      "在 SEVEN 院長的事情曝光後，病院荒廢許久。有一天被一個陌生神秘人收購，自從那天起，病院恢復了往日的名氣，甚至還增大擴建。而今天的故事是發生在 7 號病院裡......\n\n角色：伊人（女）、朋克（男）、飄飄（女）、奈奈（女）、餅乾（男）",
    coverImage: "/scripts/9a015240f2b29d069db39b434c6e9e13.png",
    playerCount: "5人- 3女2男",
    duration: "3小時（不需先玩「精神病院1」）",
    difficulty: "推理難度⭐",
    genre: "新手推薦",
    pricePerPerson: 500,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "野之薔薇",
    description: "日式/硬核推理/可反串/無換裝",
    storyText:
      "＊需自備智慧型手機並使用LINE功能；建議遊玩超過5本以上再體驗；硬核推理、閱讀量大＊\n\n1999年8月，報紙上鋪天蓋地地宣傳著一則新聞：「重金懸賞，探尋15年前小野隆一在家訓練離奇死亡的真相」小野隆一是一位被譽為「日本體操之父」的奧運冠軍，卻在1984年被發現死在家中。\n\n角色：遠山希子（女，記者）、尾山真理（女，律師）、宗神一（男，住持）、小野裕太（男，社長）、堂本彌生（男）、木村直人（男，偵探）",
    coverImage: "/scripts/86dd2a6aa490ee5105836e35b21d801c.jpg",
    playerCount: "6人- 4男2女",
    duration: "5小時",
    difficulty: "推理難度⭐⭐⭐⭐⭐",
    genre: "推理",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "沙影",
    description: "城限/沈浸情感/童話/馬戲團/提供換裝",
    storyText:
      "滿負盛名的流浪馬戲團突然停止了全世界巡迴演出，駐紮在雅典城郊，當地觀眾們接踵而至，只為親眼一睹那獨一無二且精彩絕倫的表演。今天，馬戲團依舊座無虛席，演出準時開始......\n\n角色：丹（男）、圖寧（男）、查理（男）、妮娜（女）、諾拉（女）、梅根（女）",
    coverImage: "/scripts/ca4bf418a1364d04db0f311512ea08d6.png",
    playerCount: "6人- 3男3女",
    duration: "4小時（建議玩超過5本以上再體驗）",
    difficulty: "推理難度⭐⭐",
    genre: "情感",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約請直接聯繫客服：IG @larpplayhardtw 或官方 LINE（https://lin.ee/woW09Ml）。",
    published: true,
  },
  {
    title: "動物監友會",
    description: "文本全新重製/動物思維/可反串/提供換裝",
    storyText:
      "49號監獄，這是一座戒備森嚴、關押動物囚犯的監獄，獄中的囚犯作惡多端。這天，獄中發生了一起凶案，所有人沒有悲傷、沒有恐懼，因為死者正是狐狸獄警……而兇手就在你們之中。\n\n角色：大灰狼、蛇絲絲、大象哥、兔兔兒、大鴿鴿、卯咪",
    coverImage: "/scripts/e78b9084ef1db0c6f25b19e7e64eaa3c.png",
    playerCount: "6人- 3男3女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐",
    genre: "推理",
    pricePerPerson: 600,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "畸形屋",
    description: "全民大推/微恐怖本/歐式古堡/可反串/提供換裝",
    storyText:
      "吸血女伯爵伊麗莎白的大宅遺址，傳說每當深夜天花板總是吱吱作響。今夜，又是一個暴風雨的夜晚，意外的跳電使眾人陷入黑暗之中。電力恢復之時，一個身著洋裙的女人，出現在玄關的血泊之中。\n\n角色：佩西（女，女主人）、霍默（男，少爺）、曼（男，私人醫生）、莎拉（女，女作家）、本森（男，男傭）、夏綠蒂（女，女管家）",
    coverImage: "/scripts/654b488f4aa2bd277c594c7ab4cc5618.png",
    playerCount: "6人- 3男3女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "新手推薦",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "凌汛",
    description: "制服滿滿/新手校園/可反串/提供換裝",
    storyText:
      "2017年4月23日，拜泉二中並不太平，二年八班的教室裡，兩名教師召集了五位學生，因為今天他們共同認識的學生孟晗離奇失蹤。根據監控畫面顯示，孟晗曾在今天早晨進入學校，之後再也沒有離開。\n\n角色：蘇江（男，班導師）、李浩（男，學生）、肖霄（男，學生）、肖霞（女，學生）、王淼（女，轉學生）、佟河（女）、孟濤（男，數學老師）",
    coverImage: "/scripts/604d0660c7267bb2bc332b465f1d73cd.png",
    playerCount: "6-7人- 3男3女",
    duration: "3小時",
    difficulty: "推理難度⭐⭐（隱藏結局⭐⭐⭐⭐）",
    genre: "新手推薦",
    pricePerPerson: null,
    priceGroup: 3900,
    isContactOnly: false,
    bookingNote: null,
    published: true,
  },
  {
    title: "謀殺安徒生",
    description: "#搞怪童話 #中二機制大亂鬥 #暗黑反轉",
    storyText:
      "遙遠的故事王國中，人和動物幸福相處，不存在傷痛苦難。森林中白雪公主的王冠，落地化成一抹鮮紅蘋果，被誰撿起視若珍寶一樣。是誰在講笑話？小木偶在講著故事，你在聽嗎？\n\n角色：小紅帽（女）、白雪公主（女）、灰姑娘（女）、王子（男）、騎士（男）、獵人（男）",
    coverImage: "/scripts/9fd801960815b0082d77c31038fa267a.png",
    playerCount: "6人- 3男3女",
    duration: "4.5小時",
    difficulty: "推理難度⭐⭐",
    genre: "歡樂",
    pricePerPerson: 650,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約此遊戲請直接私訊「芋薇私團」IG：larp_taroice_val（或中文：芋薇私團）。非玩硬劇本館上架劇本，無法使用玩硬相關優惠。",
    published: true,
  },
  {
    title: "洗劫巴黎所有的星星",
    description: "#歐式浪漫愛情 #詩人與科學家 #菲爾餐廳上工啦",
    storyText:
      "2023年3月11日凌晨，一顆極亮的流星劃過巴黎夜空，最終墜落在郊外的山坳，據悉現保存在羅浮宮內。同一時間，新開的拉菲餐廳裏正坐著六個人，他們是這家餐廳的員工，但他們還有一份共同的副業等待著開啟......\n\n角色：埃里克斯（男）、索瓦（男）、喬尼（男）、安娜（女）、麗薩（女）、凱瑟琳（女）",
    coverImage: "/scripts/7088e61ea2ce6c7826ec1d0b2c2bff61.png",
    playerCount: "6人- 3男3女",
    duration: "4小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "情感",
    pricePerPerson: 700,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約此遊戲請直接私訊「芋薇私團」IG：larp_taroice_val（或中文：芋薇私團）。非玩硬劇本館上架劇本，無法使用玩硬相關優惠。",
    published: true,
  },
  {
    title: "洗劫羅馬所有的情書",
    description: "#歐式浪漫愛情 #羅馬旅程 #歡迎登上菲爾的大巴車",
    storyText:
      "當黃昏漸落，一輛大巴車突兀出現，橫衝直撞著，只為趕上那場最為盛大的馬戲團表演。這可苦了車裡的六位演員，一切並非出於自願，而是一場精心策劃的綁架⋯⋯歡迎光臨，這是我們的最後一站了。\n\n角色：維托（男）、修（男）、馬爾斯（男）、黛琳（女）、菲奧娜（女）、艾達（女）",
    coverImage: "/scripts/5f0408a69d30f6eb65e934ea93a87dc5.jpg",
    playerCount: "6人- 3男3女",
    duration: "5小時",
    difficulty: "推理難度⭐⭐⭐",
    genre: "情感",
    pricePerPerson: 750,
    priceGroup: null,
    isContactOnly: true,
    bookingNote:
      "預約此遊戲請直接私訊「芋薇私團」IG：larp_taroice_val（或中文：芋薇私團）。非玩硬劇本館上架劇本，無法使用玩硬相關優惠。",
    published: true,
  },
];
